import { useState } from 'react';
import { ArrowRight, BarChart3, Bot, LayoutDashboard, LogOut, ShieldCheck, Users, Zap } from 'lucide-react';
import { AuthPage, UserBadge, useAuth } from './Auth';

const menu = ['Overview','SEO Tools','AI Content','Automation','Analytics','CRM'];

export default function Portal({ admin = false }: { admin?: boolean }) {
  const { user, loading, signOut } = useAuth();
  const [active, setActive] = useState('Overview');
  if (loading) return <div className="portal-loading">Loading secure workspace…</div>;
  if (!user) return <AuthPage onBack={() => { window.location.href = '/'; }} />;
  if (admin && !user.owner) return <div className="portal-loading"><div className="auth-card"><ShieldCheck size={42}/><h1>Owner access required</h1><p>This area is protected. Your Google account is signed in, but it is not an owner account.</p><button className="primary" onClick={() => { window.location.href='/dashboard'; }}>Go to Dashboard <ArrowRight size={16}/></button></div></div>;
  return <div className="portal"><aside><a className="brand" href="/"><span className="logo">C</span> Crazy SEO Team</a><div className="portal-label">{admin ? 'OWNER CONSOLE' : 'WORKSPACE'}</div>{menu.map((item,i)=><button className={active===item?'active':''} onClick={()=>setActive(item)} key={item}>{i===0?<LayoutDashboard/>:i===1?<BarChart3/>:i===2?<Bot/>:i===3?<Zap/>:i===5?<Users/>:<BarChart3/>}{item}</button>)}{admin && <div className="owner-box"><ShieldCheck/><div><b>Owner mode</b><small>Full platform control</small></div></div>}<button className="logout" onClick={async()=>{await signOut();window.location.href='/';}}><LogOut/> Logout</button></aside><main><header className="portal-header"><div><small>{admin?'Admin / Owner':'User'} Dashboard</small><h1>{active}</h1></div><UserBadge user={user} onLogout={async()=>{await signOut();window.location.href='/';}}/></header><section className="portal-grid"><div className="portal-card"><small>SEO Health Score</small><strong>94<span>/100</span></strong><div className="progress"><i style={{width:'94%'}}/></div><p>Technical health is strong.</p></div><div className="portal-card"><small>AI Visibility</small><strong>91<span>/100</span></strong><div className="progress"><i style={{width:'91%'}}/></div><p>Strong visibility across answer engines.</p></div><div className="portal-card"><small>LLM Optimization</small><strong>88<span>/100</span></strong><div className="progress"><i style={{width:'88%'}}/></div><p>Improve semantic coverage for higher visibility.</p></div><div className="portal-card"><small>Active Leads</small><strong>126</strong><p>+18 this month</p></div></section><section className="portal-main"><div className="portal-card large"><div className="card-head"><h2>{active} workspace</h2><span className="live-dot">● Live</span></div><p>Welcome, {user.name}. Your Crazy SEO Team workspace is connected to your Google account.</p><div className="action-row"><button className="primary">Run Analysis <ArrowRight size={16}/></button><button className="secondary">Create Project</button></div></div>{admin && <div className="portal-card large"><div className="card-head"><h2>Owner controls</h2><ShieldCheck/></div><div className="admin-list"><p><b>Authentication</b><span>Google OAuth enabled</span></p><p><b>Role</b><span>Owner</span></p><p><b>Account</b><span>{user.email}</span></p><p><b>Admin route</b><span>/admin</span></p></div></div>}</section></main></div>;
}
